In [1]:
import pandas as pd
url = "C:/1234/x_train_money.csv"
df = pd.read_csv(url, names=['F1','F2','F3','F4','F5','D1','D2','D3','D4','D5','D6','D7','D8','D9','D10','M1'])
df.head()

,F1,F2,F3,F4,F5,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,M1
0,-0.92575,-0.34309,1,-1,-1,0.0,-0.77778,-0.333330,0.189970,-0.50,0.66667,-0.76822,-0.90476,-0.001805,-0.83019,9
1,-0.92575,-0.34309,1,-1,-1,-0.8,-0.77778,-0.333330,-1.000000,-0.75,-0.66667,-0.86023,-0.80952,-0.001805,-1.00000,67
2,-0.90100,-0.46830,1,-1,-1,-0.7,-0.55556,-0.057191,-0.349560,-0.50,-0.66667,-0.90117,-0.90476,-0.001805,-0.96226,10
3,-0.86940,-0.57487,-1,1,-1,-0.9,-0.77778,-0.333330,-0.719870,-0.75,-0.83333,-1.00000,-1.00000,-0.001805,-0.98113,36
4,-0.93839,-0.25525,1,-1,-1,-0.4,-0.55556,-0.057191,-0.030911,-0.50,-0.33333,-0.77900,-0.80952,-0.001805,-0.90566,35

In [2]:
from sklearn.preprocessing import StandardScaler  # 표준화 패키지 라이브러리 
y = df['M1'].values # 종속변인 추출
x = df.drop(['M1'], axis=1).values # 독립변인들의 value값만 추출

features = ['F1','F2','F3','F4','F5','D1','D2','D3','D4','D5','D6','D7','D8','D9','D10']
pd.DataFrame(x, columns=features).head()

,F1,F2,F3,F4,F5,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10
0,-0.92575,-0.34309,1.0,-1.0,-1.0,0.0,-0.77778,-0.333330,0.189970,-0.50,0.66667,-0.76822,-0.90476,-0.001805,-0.83019
1,-0.92575,-0.34309,1.0,-1.0,-1.0,-0.8,-0.77778,-0.333330,-1.000000,-0.75,-0.66667,-0.86023,-0.80952,-0.001805,-1.00000
2,-0.90100,-0.46830,1.0,-1.0,-1.0,-0.7,-0.55556,-0.057191,-0.349560,-0.50,-0.66667,-0.90117,-0.90476,-0.001805,-0.96226
3,-0.86940,-0.57487,-1.0,1.0,-1.0,-0.9,-0.77778,-0.333330,-0.719870,-0.75,-0.83333,-1.00000,-1.00000,-0.001805,-0.98113
4,-0.93839,-0.25525,1.0,-1.0,-1.0,-0.4,-0.55556,-0.057191,-0.030911,-0.50,-0.33333,-0.77900,-0.80952,-0.001805,-0.90566

In [3]:
from sklearn.decomposition import PCA
pca = PCA(n_components=6) # 주성분을 몇개로 할지 결정
printcipalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data=printcipalComponents, columns = ['PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6'])
# 주성분으로 이루어진 데이터 프레임 구성

In [4]:
principalDf.head()

        PC1       PC2       PC3       PC4       PC5       PC6
0  2.000999 -0.493902  0.423575  1.313542  0.341464 -0.278764
1  1.565895 -0.718734  0.063482 -0.406867  0.237898 -0.228048
2  1.758098 -0.528150  0.209430 -0.155319  0.653311  0.094598
3  0.226975  1.790326  0.306106 -0.489949  0.085710 -0.316453
4  1.939779 -0.475180  0.354901  0.351514  0.643559  0.038660

In [5]:
pca.explained_variance_ratio_

array([0.37036693, 0.28037748, 0.20838995, 0.04891114, 0.0301503 ,
       0.02957917])

In [6]:
sum(pca.explained_variance_ratio_)

0.9677749619393654

In [7]:
abs(df.corr())

,F1,F2,F3,F4,F5,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,M1
F1,1.000000,0.780154,0.484293,0.336352,0.191745,0.325611,0.506563,0.571236,0.458748,0.542941,0.336020,0.298089,0.309078,0.028839,0.204834,0.266762
F2,0.780154,1.000000,0.773567,0.242156,0.130378,0.363723,0.616799,0.685700,0.533551,0.674135,0.370122,0.382514,0.428615,0.041543,0.179737,0.310665
F3,0.484293,0.773567,1.000000,0.224337,0.240912,0.295758,0.376335,0.396441,0.267443,0.426581,0.297910,0.408927,0.498229,0.063925,0.055395,0.279636
F4,0.336352,0.242156,0.224337,1.000000,0.195240,0.122834,0.467280,0.558860,0.521897,0.465480,0.128775,0.062643,0.126073,0.007051,0.220072,0.088758
F5,0.191745,0.130378,0.240912,0.195240,1.000000,0.043916,0.180950,0.200141,0.167527,0.193387,0.037964,0.036131,0.058258,0.032278,0.014171,0.035349
D1,0.325611,0.363723,0.295758,0.122834,0.043916,1.000000,0.287974,0.301815,0.604690,0.343560,0.975366,0.792441,0.656254,0.059266,0.846443,0.254639
D2,0.506563,0.616799,0.376335,0.467280,0.180950,0.287974,1.000000,0.959887,0.726558,0.864033,0.269921,0.256934,0.238935,0.086986,0.232746,0.212527
D3,0.571236,0.685700,0.396441,0.558860,0.200141,0.301815,0.959887,1.000000,0.782110,0.918338,0.286999,0.249358,0.229250,0.039722,0.242608,0.210154
D4,0.458748,0.533551,0.267443,0.521897,0.167527,0.604690,0.726558,0.782110,1.000000,0.831956,0.587206,0.408019,0.299162,0.017122,0.596839,0.232791
D5,0.542941,0.674135,0.426581,0.465480,0.193387,0.343560,0.864033,0.918338,0.831956,1.000000,0.320865,0.318763,0.292097,0.009120,0.282878,0.210911
D6,0.336020,0.370122,0.297910,0.128775,0.037964,0.975366,0.269921,0.286999,0.587206,0.320865,1.000000,0.720345,0.589108,0.059081,0.844684,0.245963
D7,0.298089,0.382514,0.408927,0.062643,0.036131,0.792441,0.256934,0.249358,0.408019,0.318763,0.720345,1.000000,0.950864,0.021944,0.480281,0.222863
D8,0.309078,0.428615,0.498229,0.126073,0.058258,0.656254,0.238935,0.229250,0.299162,0.292097,0.589108,0.950864,1.000000,0.030166,0.276340,0.219675
D9,0.028839,0.041543,0.063925,0.007051,0.032278,0.059266,0.086986,0.039722,0.017122,0.009120,0.059081,0.021944,0.030166,1.000000,0.059409,0.167646
D10,0.204834,0.179737,0.055395,0.220072,0.014171,0.846443,0.232746,0.242608,0.596839,0.282878,0.844684,0.480281,0.276340,0.059409,1.000000,0.218940
M1,0.266762,0.310665,0.279636,0.088758,0.035349,0.254639,0.212527,0.210154,0.232791,0.210911,0.245963,0.222863,0.219675,0.167646,0.218940,1.000000

In [8]:
url = "C:/1234/x_train_money_after_pca.csv"
train = pd.read_csv(url, names=['F1','F2','F3','D1','D4','D6','M1'])
train.head()

        F1       F2  F3   D1        D4       D6  M1
0 -0.92575 -0.34309   1  0.0  0.189970  0.66667   9
1 -0.92575 -0.34309   1 -0.8 -1.000000 -0.66667  67
2 -0.90100 -0.46830   1 -0.7 -0.349560 -0.66667  10
3 -0.86940 -0.57487  -1 -0.9 -0.719870 -0.83333  36
4 -0.93839 -0.25525   1 -0.4 -0.030911 -0.33333  35

In [9]:
import numpy as np
y_train=np.array(train['M1'])
x_train=train.drop(['M1'], axis=1)
x_train=np.array(x_train)

In [10]:
from sklearn.model_selection import KFold

In [11]:
kfold = KFold(n_splits=5, shuffle = True, random_state=1234)

In [12]:
from sklearn.svm import SVR
from sklearn.model_selection import cross_val_score, cross_validate

svm_model = SVR(kernel='rbf')
svm_model.fit(x_train, y_train)

SVR()

In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(svm_model , x_train , y_train ,cv=kfold)
print(scores)

In [13]:
url = "C:/1234/x_test_money_after_pca.csv"
test = pd.read_csv(url, names=['F1','F2','F3','D1','D4','D6'])

In [14]:
y_test = svm_model.predict(test)

c:\Users\hooki\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but SVR was fitted without feature names
  warnings.warn(

In [ ]:
import csv

In [ ]:
y_o = pd.DataFrame(y_test)

In [ ]:
y_o.to_csv("C:/1234/y_test_output_after_pca_money.csv")